"""Ingredient ID dropped

Revision ID: 318cb0943c6a
Revises: a10975a8d75b
Create Date: 2024-03-03 10:20:30.670911

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '318cb0943c6a'
down_revision = 'a10975a8d75b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ingredient', schema=None) as batch_op:
        batch_op.drop_column('id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ingredient', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.INTEGER(), nullable=False))

    # ### end Alembic commands ###
